#pragma once
#ifndef PERSONDATA_H
#define PERSONDATA_H
#include <string>
using namespace std;
class PersonData
{
private:
	string lastName, firstName, address, city, state, zip, phone;
	int IDnum;
public:

	PersonData()
	{
		lastName = "";
		firstName = "";
		address = "";
		city = "";
		state = "";
		zip = "";
		phone = "";
		IDnum = 0;
	}

	//mutator methods

	void setLastName(string name)
	{
		lastName = name;
	}
	void setFirstName(string name)
	{
		firstName = name;
	}
	void setAddress(string addy)
	{
		address = addy;
	}
	void setCity(string citi)
	{
		city = citi;
	}
	void setState(string stayte)
	{
		state = stayte;
	}
	void setZip(string zippy)
	{
		zip = zippy;
	}
	void setPhone(string number)
	{
		phone = number;
	}

	//accessor methods

	string getLastName()
	{
		return lastName;
	}
	string getFirstName()
	{
		return firstName;
	}
	string getAddress()
	{
		return address;
	}
	string getCity()
	{
		return city;
	}
	string getState()
	{
		return state;
	}
	string getZip()
	{
		return zip;
	}
	string getPhone()
	{
		return phone;
	}


	//this method should only be executed with generated numbers 
	// NEVER set by user
	void setID(int ID)
	{
		IDnum = ID;
	}

	//concrete ID, generated by the program and not modifyable.
	int getID()
	{
		return IDnum;
	}


};

#endif


